import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"], // especifica os pesos que quer
  variable: "--font-roboto",
  subsets: ["latin"],
});

const pressStart2p = localFont({
  src: [
    {
      path: "../public/fonts/PressStart2p.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-press-start-2p",
});

export const metadata: Metadata = {
  title: "Masi Maker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${pressStart2p.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
